name: CI - Slaine

on:
  push:
    paths:
      - '.github/**'
      - 'slaine/**'

jobs:

  format:
    name: Check format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./slaine

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./slaine

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: cargo clippy --all-targets --all-features --verbose -- -D warnings

  test:
    name: Test 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./slaine

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test

