name: CI

on:
  push:
    paths:
      - '.github/**'
      - 'sabia/**'

jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sabia

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.17
        with:
          elixir-version: '1.17'
          otp-version: '27.0'      # [Required] Define the Erlang/OTP version
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Test
        run: mix test
      - name: Credo
        run: mix credo -a --strict
      - name: Dialyzer
        run: mix dialyzer
